#!/usr/bin/env python3
"""Write bucket/frc-mcp.json for a release from its (verified) checksums.txt.

usage: manifest.py VERSION CHECKSUMS_TXT
"""
import json
import re
import sys

REPO = "https://github.com/fikretyukselit/frc-mcp"


def main() -> None:
    version, checksums = sys.argv[1], sys.argv[2]
    if not re.fullmatch(r"\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?", version):
        sys.exit(f"bad version {version!r}")
    sums = dict(reversed(line.split()) for line in open(checksums, encoding="utf-8"))
    def arch(a):
        name = f"frc-mcp_{version}_windows_{a}.zip"
        if not re.fullmatch(r"[0-9a-f]{64}", sums.get(name, "")):
            sys.exit(f"no sha256 for {name}")
        return {"url": f"{REPO}/releases/download/v{version}/{name}", "hash": sums[name]}
    m = {
        "##": "Generated by .github/workflows/update.yml from the signed frc-mcp release. Do not edit.",
        "version": version,
        "description": "Version-correct FRC robotics software knowledge for coding agents (MCP server)",
        "homepage": REPO,
        "license": "MIT",
        "architecture": {"64bit": arch("amd64"), "arm64": arch("arm64")},
        "bin": "frc-mcp.exe",
    }
    print(json.dumps(m, indent=4))


if __name__ == "__main__":
    main()
